### ISSUE TITLE
Input handler should not make user-input names all lower case

### ISSUE THREAD

**Issue by caveness** [jpikel/Pavo_Adventure#10]
When the user inputs their name, the input handler makes that name lower case. So, when the game prints out messages with the player's name, the name is in all lower case. The name should retain whatever capitalization the user specified (for names, this will typically be init-caps). 

For example, if the player inputs that their name is "Emily", when the player dies, the game should print: "Sadly, Emily died..." not "Sadly, emily died...".

**Comment by jpikel** [comment]
should be fixed with 7d3d5ca08bfaade5edea7cb3ead4e3b3e2b28b74
