### ISSUE TITLE
Game Play: Typing 'New Game' at initial prompt does not produce expected results

### ISSUE THREAD

**Issue by caveness** [jpikel/Pavo_Adventure#4]
When I start a new game and type 'New Game' at the initial prompt, the game prompts again with 'Please choose new game, load game or quit:'. Typing 'new game' (all lower case) then works.

**Comment by alaquitara** [comment]
I just modified the

**Comment by alaquitara** [comment]
I modified the input handler function to change all input to lower case behind the scenes
