### ISSUE TITLE
Tweak inventory printing to separate last two words with 'and'

### ISSUE THREAD

**Issue by caveness** [jpikel/Pavo_Adventure#6]
**This is a nice-to-have, but is in no way necessary or even important.**

Currently, if the player has two items in their inventory, the printout for the inventory command is: "Rummaging through your belongings you find a can of sweetened condensed milk, a
boat paddle". It might be good to have that read: "Rummaging through your belongings you find a can of sweetened condensed milk and a boat paddle". It would also be nice if there are three or more items in the inventory to have an 'and' separate the last two items in the list.

**Comment by jpikel** [comment]
Should be working now.
in commit 0c501fc58073806bbfefb0a6a108a2e26d4f207b
