### ISSUE TITLE
If the player responds 'n' to both prompts after entering 'quit', the game prints an extraneous 'Sorry I did not understand that.' message

### ISSUE THREAD

**Issue by caveness** [jpikel/Pavo_Adventure#9]
See the following sequence of commands and game responses:
What would you like to do?
->quit

Are you sure you want to quit without saving? y/n
->n

Do you wish to save and quit? y/n
->n
continuing game...

Sorry I did not understand that.
 What would you like to do?
->

There should not be a 'Sorry I did not understand that.' message after 'continuing game...'

**Comment by alaquitara** [comment]
Issue resolved in input_cycle method of game
